-- SQLite version of TBL_ACCOUNT table
DROP TABLE IF EXISTS TBL_ACCOUNT;

CREATE TABLE TBL_ACCOUNT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACCOUNT TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    NAME TEXT NOT NULL DEFAULT '',
    BIRTHDAY TEXT NOT NULL DEFAULT '1970/1/1',
    Q1 TEXT NOT NULL DEFAULT '',
    A1 TEXT NOT NULL DEFAULT '',
    Q2 TEXT NOT NULL DEFAULT '',
    A2 TEXT NOT NULL DEFAULT '',
    PHONENUMBER TEXT NOT NULL DEFAULT '',
    MOBILEPHONENUMBER TEXT NOT NULL DEFAULT '',
    IDCARD TEXT NOT NULL DEFAULT '',
    EMAIL TEXT NOT NULL DEFAULT '',
    FLAG INTEGER NOT NULL DEFAULT 0,
    SERVERINDEX INTEGER NOT NULL DEFAULT 0,
    CREATEDATE TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STOPED INTEGER NOT NULL DEFAULT 0,
    STOPDATE TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create index on ACCOUNT for faster lookups
CREATE INDEX idx_account_account ON TBL_ACCOUNT(ACCOUNT);
