-- SQLite version of TBL_CHARACTER_TASK table
DROP TABLE IF EXISTS TBL_CHARACTER_TASK;

CREATE TABLE TBL_CHARACTER_TASK (
    CHARID INTEGER NOT NULL DEFAULT 0,
    ACHIEVEMENT INTEGER NOT NULL DEFAULT 0,
    TASKID1 INTEGER NOT NULL DEFAULT 0,
    TASKSTEP1 INTEGER NOT NULL DEFAULT 0,
    TASKID2 INTEGER NOT NULL DEFAULT 0,
    TASKSTEP2 INTEGER NOT NULL DEFAULT 0,
    TASKID3 INTEGER NOT NULL DEFAULT 0,
    TASKSTEP3 INTEGER NOT NULL DEFAULT 0,
    TASKID4 INTEGER NOT NULL DEFAULT 0,
    TASKSTEP4 INTEGER NOT NULL DEFAULT 0,
    TASKID5 INTEGER NOT NULL DEFAULT 0,
    TASKSTEP5 INTEGER NOT NULL DEFAULT 0,
    TASKID6 INTEGER NOT NULL DEFAULT 0,
    TASKSTEP6 INTEGER NOT NULL DEFAULT 0,
    TASKID7 INTEGER NOT NULL DEFAULT 0,
    TASKSTEP7 INTEGER NOT NULL DEFAULT 0,
    TASKID8 INTEGER NOT NULL DEFAULT 0,
    TASKSTEP8 INTEGER NOT NULL DEFAULT 0,
    TASKID9 INTEGER NOT NULL DEFAULT 0,
    TASKSTEP9 INTEGER NOT NULL DEFAULT 0,
    TASKID10 INTEGER NOT NULL DEFAULT 0,
    TASKSTEP10 INTEGER NOT NULL DEFAULT 0,
    FLAGS TEXT NOT NULL DEFAULT ''
);

-- Create index for faster lookups
CREATE INDEX idx_character_task_charid ON TBL_CHARACTER_TASK(CHARID);
