-- SQLite version of TBL_CHARACTER_MAGIC table
DROP TABLE IF EXISTS TBL_CHARACTER_MAGIC;

CREATE TABLE TBL_CHARACTER_MAGIC (
    CHARID INTEGER NOT NULL DEFAULT 0,
    USERKEY INTEGER NOT NULL DEFAULT 0,
    CURLEVEL INTEGER NOT NULL DEFAULT 0,
    MAGICID INTEGER NOT NULL DEFAULT 0,
    CURTRAIN INTEGER NOT NULL DEFAULT 0,
    LEARNDATE TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for faster lookups
CREATE INDEX idx_character_magic_charid ON TBL_CHARACTER_MAGIC(CHARID);
CREATE INDEX idx_character_magic_magicid ON TBL_CHARACTER_MAGIC(MAGICID);
