-- SQLite version of TBL_CHARACTER_COMMUNITY table
DROP TABLE IF EXISTS TBL_CHARACTER_COMMUNITY;

CREATE TABLE TBL_CHARACTER_COMMUNITY (
    OWNERID INTEGER NOT NULL DEFAULT 0,
    NAME TEXT NOT NULL DEFAULT '',
    MARRIAGE TEXT NOT NULL DEFAULT '',
    MASTER TEXT NOT NULL DEFAULT '',
    STUDENT1 TEXT NOT NULL DEFAULT '',
    STUDENT2 TEXT NOT NULL DEFAULT '',
    STUDENT3 TEXT NOT NULL DEFAULT '',
    FRIEND1 TEXT NOT NULL DEFAULT '',
    FRIEND2 TEXT NOT NULL DEFAULT '',
    FRIEND3 TEXT NOT NULL DEFAULT '',
    FRIEND4 TEXT NOT NULL DEFAULT '',
    FRIEND5 TEXT NOT NULL DEFAULT '',
    FRIEND6 TEXT NOT NULL DEFAULT '',
    FRIEND7 TEXT NOT NULL DEFAULT '',
    FRIEND8 TEXT NOT NULL DEFAULT '',
    FRIEND9 TEXT NOT NULL DEFAULT '',
    FRIEND10 TEXT NOT NULL DEFAULT '',
    FRIEND11 TEXT NOT NULL DEFAULT '',
    FRIEND12 TEXT NOT NULL DEFAULT '',
    FRIEND13 TEXT NOT NULL DEFAULT '',
    FRIEND14 TEXT NOT NULL DEFAULT '',
    FRIEND15 TEXT NOT NULL DEFAULT '',
    FRIEND16 TEXT NOT NULL DEFAULT '',
    FRIEND17 TEXT NOT NULL DEFAULT '',
    FRIEND18 TEXT NOT NULL DEFAULT '',
    FRIEND19 TEXT NOT NULL DEFAULT '',
    FRIEND20 TEXT NOT NULL DEFAULT '',
    FRIEND21 TEXT NOT NULL DEFAULT '',
    FRIEND22 TEXT NOT NULL DEFAULT '',
    FRIEND23 TEXT NOT NULL DEFAULT '',
    FRIEND24 TEXT NOT NULL DEFAULT '',
    FRIEND25 TEXT NOT NULL DEFAULT '',
    FRIEND26 TEXT NOT NULL DEFAULT '',
    FRIEND27 TEXT NOT NULL DEFAULT '',
    FRIEND28 TEXT NOT NULL DEFAULT '',
    FRIEND29 TEXT NOT NULL DEFAULT '',
    FRIEND30 TEXT NOT NULL DEFAULT '',
    FRIEND31 TEXT NOT NULL DEFAULT '',
    FRIEND32 TEXT NOT NULL DEFAULT ''
);

-- Create index for faster lookups
CREATE INDEX idx_character_community_owner ON TBL_CHARACTER_COMMUNITY(OWNERID);
