-- SQLite version of TBL_CHARACTER_ITEM table
DROP TABLE IF EXISTS TBL_CHARACTER_ITEM;

CREATE TABLE TBL_CHARACTER_ITEM (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    OWNERID INTEGER NOT NULL DEFAULT 0,
    NAME TEXT NOT NULL DEFAULT 'NONAME',
    MINDC INTEGER NOT NULL DEFAULT 0,
    MAXDC INTEGER NOT NULL DEFAULT 0,
    MINMC INTEGER NOT NULL DEFAULT 0,
    MAXMC INTEGER NOT NULL DEFAULT 0,
    MINSC INTEGER NOT NULL DEFAULT 0,
    MAXSC INTEGER NOT NULL DEFAULT 0,
    MINAC INTEGER NOT NULL DEFAULT 0,
    MAXAC INTEGER NOT NULL DEFAULT 0,
    MINMAC INTEGER NOT NULL DEFAULT 0,
    MAXMAC INTEGER NOT NULL DEFAULT 0,
    DURA INTEGER NOT NULL DEFAULT 0,
    CURDURA INTEGER NOT NULL DEFAULT 0,
    MAXDURA INTEGER NOT NULL DEFAULT 0,
    NEEDTYPE INTEGER NOT NULL DEFAULT 0,
    NEEDLEVEL INTEGER NOT NULL DEFAULT 0,
    SPECIALPOWER INTEGER NOT NULL DEFAULT 0,
    NEEDIDENTIFY INTEGER NOT NULL DEFAULT 0,
    WEIGHT INTEGER NOT NULL DEFAULT 0,
    STDMODE INTEGER NOT NULL DEFAULT 0,
    SHAPE INTEGER NOT NULL DEFAULT 0,
    PRICE INTEGER NOT NULL DEFAULT 0,
    UNKNOWN_1 INTEGER NOT NULL DEFAULT 0,
    UNKNOWN_2 INTEGER NOT NULL DEFAULT 0,
    FLAG INTEGER NOT NULL DEFAULT 0,
    DELDATE TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATEDATE TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELFLAG INTEGER NOT NULL DEFAULT 0,
    DELREASON INTEGER NOT NULL DEFAULT 0,
    POS INTEGER NOT NULL DEFAULT 0,
    FINDKEY INTEGER NOT NULL DEFAULT 0,
    IMAGEINDEX INTEGER NOT NULL DEFAULT 0
);

-- Create indexes for faster lookups
CREATE INDEX idx_character_item_owner ON TBL_CHARACTER_ITEM(OWNERID);
CREATE INDEX idx_character_item_name ON TBL_CHARACTER_ITEM(NAME);
