-- MySQL version of TBL_ACCOUNT table
DROP TABLE IF EXISTS TBL_ACCOUNT;

CREATE TABLE TBL_ACCOUNT (
    ID INT NOT NULL AUTO_INCREMENT,
    ACCOUNT VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    NAME VARCHAR(50) NOT NULL DEFAULT '',
    BIRTHDAY VARCHAR(50) NOT NULL DEFAULT '1970/1/1',
    Q1 VARCHAR(50) NOT NULL DEFAULT '',
    A1 VARCHAR(50) NOT NULL DEFAULT '',
    Q2 VARCHAR(50) NOT NULL DEFAULT '',
    A2 VARCHAR(50) NOT NULL DEFAULT '',
    PHONENUMBER VARCHAR(50) NOT NULL DEFAULT '',
    MOBILEPHONENUMBER VARCHAR(50) NOT NULL DEFAULT '',
    IDCARD VARCHAR(50) NOT NULL DEFAULT '',
    EMAIL VARCHAR(50) NOT NULL DEFAULT '',
    FLAG INT NOT NULL DEFAULT 0,
    SERVERINDEX INT NOT NULL DEFAULT 0,
    CREATEDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STOPED TINYINT NOT NULL DEFAULT 0,
    STOPDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Create index on ACCOUNT for faster lookups
CREATE INDEX idx_account_account ON TBL_ACCOUNT(ACCOUNT);
