-- MySQL version of TBL_CHARACTER_ITEM table
DROP TABLE IF EXISTS TBL_CHARACTER_ITEM;

CREATE TABLE TBL_CHARACTER_ITEM (
    ID INT NOT NULL AUTO_INCREMENT,
    OWNERID INT NOT NULL DEFAULT 0,
    NAME VARCHAR(50) NOT NULL DEFAULT 'NONAME',
    MINDC TINYINT NOT NULL DEFAULT 0,
    MAXDC TINYINT NOT NULL DEFAULT 0,
    MINMC TINYINT NOT NULL DEFAULT 0,
    MAXMC TINYINT NOT NULL DEFAULT 0,
    MINSC TINYINT NOT NULL DEFAULT 0,
    MAXSC TINYINT NOT NULL DEFAULT 0,
    MINAC TINYINT NOT NULL DEFAULT 0,
    MAXAC TINYINT NOT NULL DEFAULT 0,
    MINMAC TINYINT NOT NULL DEFAULT 0,
    MAXMAC TINYINT NOT NULL DEFAULT 0,
    DURA SMALLINT NOT NULL DEFAULT 0,
    CURDURA SMALLINT NOT NULL DEFAULT 0,
    MAXDURA SMALLINT NOT NULL DEFAULT 0,
    NEEDTYPE TINYINT NOT NULL DEFAULT 0,
    NEEDLEVEL TINYINT NOT NULL DEFAULT 0,
    SPECIALPOWER TINYINT NOT NULL DEFAULT 0,
    NEEDIDENTIFY TINYINT NOT NULL DEFAULT 0,
    WEIGHT TINYINT NOT NULL DEFAULT 0,
    STDMODE TINYINT NOT NULL DEFAULT 0,
    SHAPE TINYINT NOT NULL DEFAULT 0,
    PRICE INT NOT NULL DEFAULT 0,
    UNKNOWN_1 TINYINT NOT NULL DEFAULT 0,
    UNKNOWN_2 SMALLINT NOT NULL DEFAULT 0,
    FLAG TINYINT NOT NULL DEFAULT 0,
    DELDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATEDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELFLAG TINYINT NOT NULL DEFAULT 0,
    DELREASON TINYINT NOT NULL DEFAULT 0,
    POS SMALLINT NOT NULL DEFAULT 0,
    FINDKEY INT NOT NULL DEFAULT 0,
    IMAGEINDEX SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Create indexes for faster lookups
CREATE INDEX idx_character_item_owner ON TBL_CHARACTER_ITEM(OWNERID);
CREATE INDEX idx_character_item_name ON TBL_CHARACTER_ITEM(NAME);
