-- MySQL version of TBL_CHARACTER_COMMUNITY table
DROP TABLE IF EXISTS TBL_CHARACTER_COMMUNITY;

CREATE TABLE TBL_CHARACTER_COMMUNITY (
    OWNERID INT NOT NULL DEFAULT 0,
    NAME VARCHAR(50) NOT NULL DEFAULT '',
    MARRIAGE VARCHAR(50) NOT NULL DEFAULT '',
    MASTER VARCHAR(50) NOT NULL DEFAULT '',
    STUDENT1 VARCHAR(50) NOT NULL DEFAULT '',
    STUDENT2 VARCHAR(50) NOT NULL DEFAULT '',
    STUDENT3 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND1 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND2 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND3 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND4 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND5 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND6 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND7 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND8 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND9 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND10 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND11 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND12 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND13 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND14 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND15 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND16 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND17 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND18 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND19 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND20 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND21 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND22 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND23 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND24 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND25 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND26 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND27 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND28 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND29 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND30 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND31 VARCHAR(50) NOT NULL DEFAULT '',
    FRIEND32 VARCHAR(50) NOT NULL DEFAULT ''
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Create index for faster lookups
CREATE INDEX idx_character_community_owner ON TBL_CHARACTER_COMMUNITY(OWNERID);
