-- MySQL version of TBL_CHARACTER_TASK table
DROP TABLE IF EXISTS TBL_CHARACTER_TASK;

CREATE TABLE TBL_CHARACTER_TASK (
    CHARID INT NOT NULL DEFAULT 0,
    ACHIEVEMENT INT NOT NULL DEFAULT 0,
    TASKID1 INT NOT NULL DEFAULT 0,
    TASKSTEP1 INT NOT NULL DEFAULT 0,
    TASKID2 INT NOT NULL DEFAULT 0,
    TASKSTEP2 INT NOT NULL DEFAULT 0,
    TASKID3 INT NOT NULL DEFAULT 0,
    TASKSTEP3 INT NOT NULL DEFAULT 0,
    TASKID4 INT NOT NULL DEFAULT 0,
    TASKSTEP4 INT NOT NULL DEFAULT 0,
    TASKID5 INT NOT NULL DEFAULT 0,
    TASKSTEP5 INT NOT NULL DEFAULT 0,
    TASKID6 INT NOT NULL DEFAULT 0,
    TASKSTEP6 INT NOT NULL DEFAULT 0,
    TASKID7 INT NOT NULL DEFAULT 0,
    TASKSTEP7 INT NOT NULL DEFAULT 0,
    TASKID8 INT NOT NULL DEFAULT 0,
    TASKSTEP8 INT NOT NULL DEFAULT 0,
    TASKID9 INT NOT NULL DEFAULT 0,
    TASKSTEP9 INT NOT NULL DEFAULT 0,
    TASKID10 INT NOT NULL DEFAULT 0,
    TASKSTEP10 INT NOT NULL DEFAULT 0,
    FLAGS VARCHAR(1024) NOT NULL DEFAULT ''
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Create index for faster lookups
CREATE INDEX idx_character_task_charid ON TBL_CHARACTER_TASK(CHARID);
