-- MySQL version of TBL_CHARACTER_MAGIC table
DROP TABLE IF EXISTS TBL_CHARACTER_MAGIC;

CREATE TABLE TBL_CHARACTER_MAGIC (
    CHARID INT NOT NULL DEFAULT 0,
    USERKEY TINYINT NOT NULL DEFAULT 0,
    CURLEVEL TINYINT NOT NULL DEFAULT 0,
    MAGICID SMALLINT NOT NULL DEFAULT 0,
    CURTRAIN INT NOT NULL DEFAULT 0,
    LEARNDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Create indexes for faster lookups
CREATE INDEX idx_character_magic_charid ON TBL_CHARACTER_MAGIC(CHARID);
CREATE INDEX idx_character_magic_magicid ON TBL_CHARACTER_MAGIC(MAGICID);
