if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[TBL_CHARACTER_ITEM]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[TBL_CHARACTER_ITEM]
GO

CREATE TABLE [dbo].[TBL_CHARACTER_ITEM] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[OWNERID] [int] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_OWNERID] DEFAULT (0),
	[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_NAME] DEFAULT ('NONAME'),
	[MINDC] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_MINDC] DEFAULT (0),
	[MAXDC] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_MAXDC] DEFAULT (0),
	[MINMC] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_MINMC] DEFAULT (0),
	[MAXMC] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_MAXMC] DEFAULT (0),
	[MINSC] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_MINSC] DEFAULT (0),
	[MAXSC] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_MAXSC] DEFAULT (0),
	[MINAC] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_MINAC] DEFAULT (0),
	[MAXAC] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_MAXAC] DEFAULT (0),
	[MINMAC] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_MINMAC] DEFAULT (0),
	[MAXMAC] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_MAXMAC] DEFAULT (0),
	[DURA] [smallint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_DURA] DEFAULT (0),
        [CURDURA] [smallint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_CURDURA] DEFAULT (0),
	[MAXDURA] [smallint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_MAXDURA] DEFAULT (0),
	[NEEDTYPE] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_NEEDTYPE] DEFAULT (0),
	[NEEDLEVEL] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_NEEDLEVEL] DEFAULT (0),
	[SPECIALPOWER] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_SPECIALPOWER] DEFAULT (0),
	[NEEDIDENTIFY] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_NEEDIDENTIFY] DEFAULT (0),
	[WEIGHT] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_WEIGHT] DEFAULT (0),
	[STDMODE] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_STDMODE] DEFAULT (0),
	[SHAPE] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_SHAPE] DEFAULT (0),
	[PRICE] [int] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_PRICE] DEFAULT (0),
	[UNKNOWN_1] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_UNKNOWN_1] DEFAULT (0),
	[UNKNOWN_2] [smallint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_UNKNOWN_2] DEFAULT (0),
	[FLAG] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_FLAG] DEFAULT (0),
	[DELDATE] [datetime] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_DELDATE] DEFAULT (getdate()),
	[CREATEDATE] [datetime] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_CREATEDATE] DEFAULT (getdate()),
	[DELFLAG] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_DELFLAG] DEFAULT (0),
	[DELREASON] [tinyint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_DELREASON] DEFAULT (0),
	[POS] [smallint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_POS] DEFAULT (0),
	[FINDKEY] [int] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_FINDKEY] DEFAULT (0),
	[IMAGEINDEX] [smallint] NOT NULL CONSTRAINT [DF_TBL_CHARACTER_ITEM_IMAGEINDEX] DEFAULT (0)
) ON [PRIMARY]
GO


