if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[TBL_CHARACTER_MAGIC]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[TBL_CHARACTER_MAGIC]
GO

CREATE TABLE [dbo].[TBL_CHARACTER_MAGIC] (
	[CHARID] [int] NOT NULL ,
	[USERKEY] [tinyint] NOT NULL ,
	[CURLEVEL] [tinyint] NOT NULL ,
	[MAGICID] [smallint] NOT NULL ,
	[CURTRAIN] [int] NOT NULL ,
	[LEARNDATE] [datetime] NOT NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBL_CHARACTER_MAGIC] WITH NOCHECK ADD 
	CONSTRAINT [DF_TBL_CHARACTER_MAGIC_CHARID] DEFAULT (0) FOR [CHARID],
	CONSTRAINT [DF_TBL_CHARACTER_MAGIC_USERKEY] DEFAULT (0) FOR [USERKEY],
	CONSTRAINT [DF_TBL_CHARACTER_MAGIC_CURLEVEL] DEFAULT (0) FOR [CURLEVEL],
	CONSTRAINT [DF_TBL_CHARACTER_MAGIC_MAGIC] DEFAULT (0) FOR [MAGICID],
	CONSTRAINT [DF_TBL_CHARACTER_MAGIC_CURTRAIN] DEFAULT (0) FOR [CURTRAIN],
	CONSTRAINT [DF_TBL_CHARACTER_MAGIC_LEARNDATE] DEFAULT (getdate()) FOR [LEARNDATE]
GO

