if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[TBL_CHARACTER_TASK]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[TBL_CHARACTER_TASK]
GO

CREATE TABLE [dbo].[TBL_CHARACTER_TASK] (
	[CHARID] [int] NOT NULL ,
	[ACHIEVEMENT] [int] NOT NULL ,
	[TASKID1] [int] NOT NULL ,
	[TASKSTEP1] [int] NOT NULL ,
	[TASKID2] [int] NOT NULL ,
	[TASKSTEP2] [int] NOT NULL ,
	[TASKID3] [int] NOT NULL ,
	[TASKSTEP3] [int] NOT NULL ,
	[TASKID4] [int] NOT NULL ,
	[TASKSTEP4] [int] NOT NULL ,
	[TASKID5] [int] NOT NULL ,
	[TASKSTEP5] [int] NOT NULL ,
	[TASKID6] [int] NOT NULL ,
	[TASKSTEP6] [int] NOT NULL ,
	[TASKID7] [int] NOT NULL ,
	[TASKSTEP7] [int] NOT NULL ,
	[TASKID8] [int] NOT NULL ,
	[TASKSTEP8] [int] NOT NULL ,
	[TASKID9] [int] NOT NULL ,
	[TASKSTEP9] [int] NOT NULL ,
	[TASKID10] [int] NOT NULL ,
	[TASKSTEP10] [int] NOT NULL ,
	[FLAGS] [varchar] (1024) COLLATE Chinese_PRC_CI_AS NOT NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBL_CHARACTER_TASK] ADD 
	CONSTRAINT [DF_TBL_CHARACTER_TASK_ACHIEVEMENT] DEFAULT ('') FOR [ACHIEVEMENT],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKID1] DEFAULT (0) FOR [TASKID1],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKSTEP1] DEFAULT (0) FOR [TASKSTEP1],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKID2] DEFAULT (0) FOR [TASKID2],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKSTEP2] DEFAULT (0) FOR [TASKSTEP2],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKID3] DEFAULT (0) FOR [TASKID3],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKSTEP3] DEFAULT (0) FOR [TASKSTEP3],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKID4] DEFAULT (0) FOR [TASKID4],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKSTEP4] DEFAULT (0) FOR [TASKSTEP4],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKID5] DEFAULT (0) FOR [TASKID5],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKSTEP5] DEFAULT (0) FOR [TASKSTEP5],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKID6] DEFAULT (0) FOR [TASKID6],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKSTEP6] DEFAULT (0) FOR [TASKSTEP6],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKID7] DEFAULT (0) FOR [TASKID7],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKSTEP7] DEFAULT (0) FOR [TASKSTEP7],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKID8] DEFAULT (0) FOR [TASKID8],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKSTEP8] DEFAULT (0) FOR [TASKSTEP8],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKID9] DEFAULT (0) FOR [TASKID9],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKSTEP9] DEFAULT (0) FOR [TASKSTEP9],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKID10] DEFAULT (0) FOR [TASKID10],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_TASKSTEP10] DEFAULT (0) FOR [TASKSTEP10],
	CONSTRAINT [DF_TBL_CHARACTER_TASK_FLAGS] DEFAULT ('') FOR [FLAGS]
GO

 CREATE  INDEX [IX_TBL_CHARACTER_TASK] ON [dbo].[TBL_CHARACTER_TASK]([CHARID]) ON [PRIMARY]
GO

