if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[TBL_ACCOUNT]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[TBL_ACCOUNT]
GO

CREATE TABLE [dbo].[TBL_ACCOUNT] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[ACCOUNT] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	[PASSWORD] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF_TBL_ACCOUNT_NAME] DEFAULT (''),
	[BIRTHDAY] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF_TBL_ACCOUNT_BIRTHDAY] DEFAULT (1970 / 1 / 1),
	[Q1] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF_TBL_ACCOUNT_Q1] DEFAULT (''),
	[A1] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF_TBL_ACCOUNT_A1] DEFAULT (''),
	[Q2] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF_TBL_ACCOUNT_Q2] DEFAULT (''),
	[A2] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF_TBL_ACCOUNT_A2] DEFAULT (''),
	[PHONENUMBER] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF_TBL_ACCOUNT_PHONENUMBER] DEFAULT (''),
	[MOBILEPHONENUMBER] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF_TBL_ACCOUNT_MOBILEPHONENUMBER] DEFAULT (''),
	[IDCARD] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF_TBL_ACCOUNT_IDCARD] DEFAULT (''),
	[EMAIL] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF_TBL_ACCOUNT_EMAIL] DEFAULT (''),
	[FLAG] [int] NOT NULL CONSTRAINT [DF_TBL_ACCOUNT_FLAG] DEFAULT (0),
	[SERVERINDEX] [int] NOT NULL CONSTRAINT [DF_TBL_ACCOUNT_SERVERINDEX] DEFAULT (0),
	[CREATEDATE] [datetime] NOT NULL CONSTRAINT [DF_TBL_ACCOUNT_CREATEDATE] DEFAULT (getdate()),
	[STOPED] [tinyint] NOT NULL CONSTRAINT [DF_TBL_ACCOUNT_STOPED] DEFAULT (0),
	[STOPDATE] [datetime] NOT NULL CONSTRAINT [DF_TBL_ACCOUNT_STOPDATE] DEFAULT (getdate())
) ON [PRIMARY]
GO


